const toyStory = [
    {
      id: 1,
      nome: "Woody",
      tipo: "Boneco",
      anoFabricacao: 1995,
      cor: "Marrom",
      quantidadeEstoque: 5,
      habilidadeEspecial: "Liderança e lealdade",
      fraseFamosa: "Tem uma cobra na minha bota!",
    },
    {
      id: 2,
      nome: "Buzz Lightyear",
      tipo: "Robô",
      anoFabricacao: 1995,
      cor: "Verde e branco",
      quantidadeEstoque: 3,
      habilidadeEspecial: "Voo intergaláctico",
      fraseFamosa: "Ao infinito e além!",
    },
    {
      id: 3,
      nome: "Jessie",
      tipo: "Boneca",
      anoFabricacao: 1999,
      cor: "Vermelha e branca",
      quantidadeEstoque: 2,
      habilidadeEspecial: "Canto e yodeling",
      fraseFamosa: "Yee-haw!",
    },
    {
      id: 4,
      nome: "Sr. Cabeça de Batata",
      tipo: "Brinquedo de montar",
      anoFabricacao: 1995,
      cor: "Marrom",
      quantidadeEstoque: 7,
      habilidadeEspecial: "Pode trocar suas partes",
      fraseFamosa: "Ei, garoto! Você não pode esmagar um esquadrão de toy soldiers.",
    },
    {
      id: 5,
      nome: "Slinky Dog",
      tipo: "Cachorro de mola",
      anoFabricacao: 1995,
      cor: "Marrom",
      quantidadeEstoque: 4,
      habilidadeEspecial: "Esticar seu corpo de mola",
      fraseFamosa: "Vá em frente, Woody, eu vou te dar um empurrãozinho.",
    },
    {
      id: 6,
      nome: "Rex",
      tipo: "Dinossauro",
      anoFabricacao: 1995,
      cor: "Verde",
      quantidadeEstoque: 1,
      habilidadeEspecial: "Rugido assustador",
      fraseFamosa: "Oh, eu sou um T-Rex! Tenho medo de tudo!",
    },
    {
      id: 7,
      nome: "Hamm",
      tipo: "Cofre",
      anoFabricacao: 1995,
      cor: "Rosa",
      quantidadeEstoque: 6,
      habilidadeEspecial: "Conhecimento sobre o mundo exterior",
      fraseFamosa: "Eu sou o Hamm! Sou o porco mais mal-humorado do mundo!",
    },
    {
      id: 8,
      nome: "Alienígenas",
      tipo: "Alienígena",
      anoFabricacao: 1995,
      cor: "Verde",
      quantidadeEstoque: 10,
      habilidadeEspecial: "Cantar em harmonia",
      fraseFamosa: "Oooohh! A garra!",
    },
    {
      id: 9,
      nome: "Betty",
      tipo: "Boneca de porcelana",
      anoFabricacao: 1995,
      cor: "Rosa",
      quantidadeEstoque: 2,
      habilidadeEspecial: "Inteligência e agilidade",
      fraseFamosa: "Não me chame de 'dama'.",
    },
    {
      id: 10,
      nome: "Soldados do Exército",
      tipo: "Soldado",
      anoFabricacao: 1995,
      cor: "Verde",
      quantidadeEstoque: 15,
      habilidadeEspecial: "Organização e disciplina",
      fraseFamosa: "Missão cumprida!",
    },
    {
      id: 11,
      nome: "Lotso",
      tipo: "Urso de pelúcia",
      anoFabricacao: 2010,
      cor: "Rosa",
      quantidadeEstoque: 0,
      habilidadeEspecial: "Falsa simpatia",
      fraseFamosa: "Eu sou Lotso, o urso de morango!",
    },
    {
      id: 12,
      nome: "Ken",
      tipo: "Boneco",
      anoFabricacao: 2010,
      cor: "Bege",
      quantidadeEstoque: 3,
      habilidadeEspecial: "Entendimento de moda",
      fraseFamosa: "Eu tenho uma casa de sonho, Barbie!",
    },
    {
      id: 13,
      nome: "Barbie",
      tipo: "Boneca",
      anoFabricacao: 1999,
      cor: "Rosa",
      quantidadeEstoque: 4,
      habilidadeEspecial: "Adaptação a qualquer situação",
      fraseFamosa: "Obrigada, Ken!",
    },
    {
      id: 14,
      nome: "Duke Caboom",
      tipo: "Motoqueiro de brinquedo",
      anoFabricacao: 2019,
      cor: "Branco",
      quantidadeEstoque: 2,
      habilidadeEspecial: "Acrobacias de moto",
      fraseFamosa: "Caboom!",
    },
    {
      id: 15,
      nome: "Forky",
      tipo: "Brinquedo artesanal",
      anoFabricacao: 2019,
      cor: "Branco e vermelho",
      quantidadeEstoque: 5,
      habilidadeEspecial: "Capacidade de se desfazer",
      fraseFamosa: "Eu não sou um brinquedo!",
    },
  ];
  
  export default { toyStory };